stages:
  - build
  - test
  - package

variables:
  RUST_BACKTRACE: 1

# Cache just the target directory for faster builds
cache:
  paths:
    - target/

# Main build job
build:
  stage: build
  tags:
    - linux
  script:
    # Verify Rust is available
    - rustc --version
    - cargo --version
    # Build
    - cargo build --release
  artifacts:
    paths:
      - target/release/

# Run tests
test:
  stage: test
  tags:
    - linux
  needs: [build]
  script:
    - cargo test

# Linux build
linux:
  stage: package
  tags:
    - linux
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/*.so
    expire_in: 1 week

# macOS build
macos:
  stage: package
  tags:
    - macos
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/*.dylib
    expire_in: 1 week

# Windows build
windows:
  stage: package
  tags:
    - windows
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/*.dll
    expire_in: 1 week
